// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

// Protobuf Java Version: 3.25.3
package game.connection.packets.messages;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:connection.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .connection.Person people = 1;</code>
   */
  java.util.List<game.connection.packets.messages.Person> 
      getPeopleList();
  /**
   * <code>repeated .connection.Person people = 1;</code>
   */
  game.connection.packets.messages.Person getPeople(int index);
  /**
   * <code>repeated .connection.Person people = 1;</code>
   */
  int getPeopleCount();
  /**
   * <code>repeated .connection.Person people = 1;</code>
   */
  java.util.List<? extends game.connection.packets.messages.PersonOrBuilder> 
      getPeopleOrBuilderList();
  /**
   * <code>repeated .connection.Person people = 1;</code>
   */
  game.connection.packets.messages.PersonOrBuilder getPeopleOrBuilder(
      int index);
}
