// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

// Protobuf Java Version: 3.25.3
package game.connection.packets.messages;

/**
 * Protobuf type {@code connection.ClientMessage}
 */
public final class ClientMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:connection.ClientMessage)
    ClientMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientMessage.newBuilder() to construct.
  private ClientMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientMessage() {
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ClientMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return game.connection.packets.messages.PacketMessages.internal_static_connection_ClientMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return game.connection.packets.messages.PacketMessages.internal_static_connection_ClientMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            game.connection.packets.messages.ClientMessage.class, game.connection.packets.messages.ClientMessage.Builder.class);
  }

  public interface InputMOrBuilder extends
      // @@protoc_insertion_point(interface_extends:connection.ClientMessage.InputM)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.connection.VectorM mousepos = 1;</code>
     * @return Whether the mousepos field is set.
     */
    boolean hasMousepos();
    /**
     * <code>.connection.VectorM mousepos = 1;</code>
     * @return The mousepos.
     */
    game.connection.packets.messages.VectorM getMousepos();
    /**
     * <code>.connection.VectorM mousepos = 1;</code>
     */
    game.connection.packets.messages.VectorMOrBuilder getMouseposOrBuilder();

    /**
     * <code>bool teleport = 2;</code>
     * @return The teleport.
     */
    boolean getTeleport();

    /**
     * <code>bool create = 3;</code>
     * @return The create.
     */
    boolean getCreate();

    /**
     * <code>bool webFling = 4;</code>
     * @return The webFling.
     */
    boolean getWebFling();

    /**
     * <code>bool detachWeb = 5;</code>
     * @return The detachWeb.
     */
    boolean getDetachWeb();
  }
  /**
   * Protobuf type {@code connection.ClientMessage.InputM}
   */
  public static final class InputM extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:connection.ClientMessage.InputM)
      InputMOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InputM.newBuilder() to construct.
    private InputM(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InputM() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new InputM();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.connection.packets.messages.PacketMessages.internal_static_connection_ClientMessage_InputM_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.connection.packets.messages.PacketMessages.internal_static_connection_ClientMessage_InputM_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.connection.packets.messages.ClientMessage.InputM.class, game.connection.packets.messages.ClientMessage.InputM.Builder.class);
    }

    private int bitField0_;
    public static final int MOUSEPOS_FIELD_NUMBER = 1;
    private game.connection.packets.messages.VectorM mousepos_;
    /**
     * <code>.connection.VectorM mousepos = 1;</code>
     * @return Whether the mousepos field is set.
     */
    @java.lang.Override
    public boolean hasMousepos() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.connection.VectorM mousepos = 1;</code>
     * @return The mousepos.
     */
    @java.lang.Override
    public game.connection.packets.messages.VectorM getMousepos() {
      return mousepos_ == null ? game.connection.packets.messages.VectorM.getDefaultInstance() : mousepos_;
    }
    /**
     * <code>.connection.VectorM mousepos = 1;</code>
     */
    @java.lang.Override
    public game.connection.packets.messages.VectorMOrBuilder getMouseposOrBuilder() {
      return mousepos_ == null ? game.connection.packets.messages.VectorM.getDefaultInstance() : mousepos_;
    }

    public static final int TELEPORT_FIELD_NUMBER = 2;
    private boolean teleport_ = false;
    /**
     * <code>bool teleport = 2;</code>
     * @return The teleport.
     */
    @java.lang.Override
    public boolean getTeleport() {
      return teleport_;
    }

    public static final int CREATE_FIELD_NUMBER = 3;
    private boolean create_ = false;
    /**
     * <code>bool create = 3;</code>
     * @return The create.
     */
    @java.lang.Override
    public boolean getCreate() {
      return create_;
    }

    public static final int WEBFLING_FIELD_NUMBER = 4;
    private boolean webFling_ = false;
    /**
     * <code>bool webFling = 4;</code>
     * @return The webFling.
     */
    @java.lang.Override
    public boolean getWebFling() {
      return webFling_;
    }

    public static final int DETACHWEB_FIELD_NUMBER = 5;
    private boolean detachWeb_ = false;
    /**
     * <code>bool detachWeb = 5;</code>
     * @return The detachWeb.
     */
    @java.lang.Override
    public boolean getDetachWeb() {
      return detachWeb_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getMousepos());
      }
      if (teleport_ != false) {
        output.writeBool(2, teleport_);
      }
      if (create_ != false) {
        output.writeBool(3, create_);
      }
      if (webFling_ != false) {
        output.writeBool(4, webFling_);
      }
      if (detachWeb_ != false) {
        output.writeBool(5, detachWeb_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMousepos());
      }
      if (teleport_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, teleport_);
      }
      if (create_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, create_);
      }
      if (webFling_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, webFling_);
      }
      if (detachWeb_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, detachWeb_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof game.connection.packets.messages.ClientMessage.InputM)) {
        return super.equals(obj);
      }
      game.connection.packets.messages.ClientMessage.InputM other = (game.connection.packets.messages.ClientMessage.InputM) obj;

      if (hasMousepos() != other.hasMousepos()) return false;
      if (hasMousepos()) {
        if (!getMousepos()
            .equals(other.getMousepos())) return false;
      }
      if (getTeleport()
          != other.getTeleport()) return false;
      if (getCreate()
          != other.getCreate()) return false;
      if (getWebFling()
          != other.getWebFling()) return false;
      if (getDetachWeb()
          != other.getDetachWeb()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMousepos()) {
        hash = (37 * hash) + MOUSEPOS_FIELD_NUMBER;
        hash = (53 * hash) + getMousepos().hashCode();
      }
      hash = (37 * hash) + TELEPORT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getTeleport());
      hash = (37 * hash) + CREATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCreate());
      hash = (37 * hash) + WEBFLING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getWebFling());
      hash = (37 * hash) + DETACHWEB_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getDetachWeb());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static game.connection.packets.messages.ClientMessage.InputM parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.connection.packets.messages.ClientMessage.InputM parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.connection.packets.messages.ClientMessage.InputM parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.connection.packets.messages.ClientMessage.InputM parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.connection.packets.messages.ClientMessage.InputM parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static game.connection.packets.messages.ClientMessage.InputM parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static game.connection.packets.messages.ClientMessage.InputM parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static game.connection.packets.messages.ClientMessage.InputM parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static game.connection.packets.messages.ClientMessage.InputM parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static game.connection.packets.messages.ClientMessage.InputM parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static game.connection.packets.messages.ClientMessage.InputM parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static game.connection.packets.messages.ClientMessage.InputM parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(game.connection.packets.messages.ClientMessage.InputM prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code connection.ClientMessage.InputM}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:connection.ClientMessage.InputM)
        game.connection.packets.messages.ClientMessage.InputMOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return game.connection.packets.messages.PacketMessages.internal_static_connection_ClientMessage_InputM_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return game.connection.packets.messages.PacketMessages.internal_static_connection_ClientMessage_InputM_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                game.connection.packets.messages.ClientMessage.InputM.class, game.connection.packets.messages.ClientMessage.InputM.Builder.class);
      }

      // Construct using game.connection.packets.messages.ClientMessage.InputM.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMouseposFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        mousepos_ = null;
        if (mouseposBuilder_ != null) {
          mouseposBuilder_.dispose();
          mouseposBuilder_ = null;
        }
        teleport_ = false;
        create_ = false;
        webFling_ = false;
        detachWeb_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return game.connection.packets.messages.PacketMessages.internal_static_connection_ClientMessage_InputM_descriptor;
      }

      @java.lang.Override
      public game.connection.packets.messages.ClientMessage.InputM getDefaultInstanceForType() {
        return game.connection.packets.messages.ClientMessage.InputM.getDefaultInstance();
      }

      @java.lang.Override
      public game.connection.packets.messages.ClientMessage.InputM build() {
        game.connection.packets.messages.ClientMessage.InputM result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public game.connection.packets.messages.ClientMessage.InputM buildPartial() {
        game.connection.packets.messages.ClientMessage.InputM result = new game.connection.packets.messages.ClientMessage.InputM(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(game.connection.packets.messages.ClientMessage.InputM result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.mousepos_ = mouseposBuilder_ == null
              ? mousepos_
              : mouseposBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.teleport_ = teleport_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.create_ = create_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.webFling_ = webFling_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.detachWeb_ = detachWeb_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof game.connection.packets.messages.ClientMessage.InputM) {
          return mergeFrom((game.connection.packets.messages.ClientMessage.InputM)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(game.connection.packets.messages.ClientMessage.InputM other) {
        if (other == game.connection.packets.messages.ClientMessage.InputM.getDefaultInstance()) return this;
        if (other.hasMousepos()) {
          mergeMousepos(other.getMousepos());
        }
        if (other.getTeleport() != false) {
          setTeleport(other.getTeleport());
        }
        if (other.getCreate() != false) {
          setCreate(other.getCreate());
        }
        if (other.getWebFling() != false) {
          setWebFling(other.getWebFling());
        }
        if (other.getDetachWeb() != false) {
          setDetachWeb(other.getDetachWeb());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getMouseposFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                teleport_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                create_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                webFling_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                detachWeb_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private game.connection.packets.messages.VectorM mousepos_;
      private com.google.protobuf.SingleFieldBuilderV3<
          game.connection.packets.messages.VectorM, game.connection.packets.messages.VectorM.Builder, game.connection.packets.messages.VectorMOrBuilder> mouseposBuilder_;
      /**
       * <code>.connection.VectorM mousepos = 1;</code>
       * @return Whether the mousepos field is set.
       */
      public boolean hasMousepos() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.connection.VectorM mousepos = 1;</code>
       * @return The mousepos.
       */
      public game.connection.packets.messages.VectorM getMousepos() {
        if (mouseposBuilder_ == null) {
          return mousepos_ == null ? game.connection.packets.messages.VectorM.getDefaultInstance() : mousepos_;
        } else {
          return mouseposBuilder_.getMessage();
        }
      }
      /**
       * <code>.connection.VectorM mousepos = 1;</code>
       */
      public Builder setMousepos(game.connection.packets.messages.VectorM value) {
        if (mouseposBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mousepos_ = value;
        } else {
          mouseposBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.connection.VectorM mousepos = 1;</code>
       */
      public Builder setMousepos(
          game.connection.packets.messages.VectorM.Builder builderForValue) {
        if (mouseposBuilder_ == null) {
          mousepos_ = builderForValue.build();
        } else {
          mouseposBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.connection.VectorM mousepos = 1;</code>
       */
      public Builder mergeMousepos(game.connection.packets.messages.VectorM value) {
        if (mouseposBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            mousepos_ != null &&
            mousepos_ != game.connection.packets.messages.VectorM.getDefaultInstance()) {
            getMouseposBuilder().mergeFrom(value);
          } else {
            mousepos_ = value;
          }
        } else {
          mouseposBuilder_.mergeFrom(value);
        }
        if (mousepos_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.connection.VectorM mousepos = 1;</code>
       */
      public Builder clearMousepos() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mousepos_ = null;
        if (mouseposBuilder_ != null) {
          mouseposBuilder_.dispose();
          mouseposBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.connection.VectorM mousepos = 1;</code>
       */
      public game.connection.packets.messages.VectorM.Builder getMouseposBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMouseposFieldBuilder().getBuilder();
      }
      /**
       * <code>.connection.VectorM mousepos = 1;</code>
       */
      public game.connection.packets.messages.VectorMOrBuilder getMouseposOrBuilder() {
        if (mouseposBuilder_ != null) {
          return mouseposBuilder_.getMessageOrBuilder();
        } else {
          return mousepos_ == null ?
              game.connection.packets.messages.VectorM.getDefaultInstance() : mousepos_;
        }
      }
      /**
       * <code>.connection.VectorM mousepos = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          game.connection.packets.messages.VectorM, game.connection.packets.messages.VectorM.Builder, game.connection.packets.messages.VectorMOrBuilder> 
          getMouseposFieldBuilder() {
        if (mouseposBuilder_ == null) {
          mouseposBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              game.connection.packets.messages.VectorM, game.connection.packets.messages.VectorM.Builder, game.connection.packets.messages.VectorMOrBuilder>(
                  getMousepos(),
                  getParentForChildren(),
                  isClean());
          mousepos_ = null;
        }
        return mouseposBuilder_;
      }

      private boolean teleport_ ;
      /**
       * <code>bool teleport = 2;</code>
       * @return The teleport.
       */
      @java.lang.Override
      public boolean getTeleport() {
        return teleport_;
      }
      /**
       * <code>bool teleport = 2;</code>
       * @param value The teleport to set.
       * @return This builder for chaining.
       */
      public Builder setTeleport(boolean value) {

        teleport_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bool teleport = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTeleport() {
        bitField0_ = (bitField0_ & ~0x00000002);
        teleport_ = false;
        onChanged();
        return this;
      }

      private boolean create_ ;
      /**
       * <code>bool create = 3;</code>
       * @return The create.
       */
      @java.lang.Override
      public boolean getCreate() {
        return create_;
      }
      /**
       * <code>bool create = 3;</code>
       * @param value The create to set.
       * @return This builder for chaining.
       */
      public Builder setCreate(boolean value) {

        create_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool create = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        create_ = false;
        onChanged();
        return this;
      }

      private boolean webFling_ ;
      /**
       * <code>bool webFling = 4;</code>
       * @return The webFling.
       */
      @java.lang.Override
      public boolean getWebFling() {
        return webFling_;
      }
      /**
       * <code>bool webFling = 4;</code>
       * @param value The webFling to set.
       * @return This builder for chaining.
       */
      public Builder setWebFling(boolean value) {

        webFling_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>bool webFling = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearWebFling() {
        bitField0_ = (bitField0_ & ~0x00000008);
        webFling_ = false;
        onChanged();
        return this;
      }

      private boolean detachWeb_ ;
      /**
       * <code>bool detachWeb = 5;</code>
       * @return The detachWeb.
       */
      @java.lang.Override
      public boolean getDetachWeb() {
        return detachWeb_;
      }
      /**
       * <code>bool detachWeb = 5;</code>
       * @param value The detachWeb to set.
       * @return This builder for chaining.
       */
      public Builder setDetachWeb(boolean value) {

        detachWeb_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>bool detachWeb = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDetachWeb() {
        bitField0_ = (bitField0_ & ~0x00000010);
        detachWeb_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:connection.ClientMessage.InputM)
    }

    // @@protoc_insertion_point(class_scope:connection.ClientMessage.InputM)
    private static final game.connection.packets.messages.ClientMessage.InputM DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new game.connection.packets.messages.ClientMessage.InputM();
    }

    public static game.connection.packets.messages.ClientMessage.InputM getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InputM>
        PARSER = new com.google.protobuf.AbstractParser<InputM>() {
      @java.lang.Override
      public InputM parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<InputM> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InputM> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public game.connection.packets.messages.ClientMessage.InputM getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INPUT_FIELD_NUMBER = 2;
  private game.connection.packets.messages.ClientMessage.InputM input_;
  /**
   * <code>.connection.ClientMessage.InputM input = 2;</code>
   * @return Whether the input field is set.
   */
  @java.lang.Override
  public boolean hasInput() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.connection.ClientMessage.InputM input = 2;</code>
   * @return The input.
   */
  @java.lang.Override
  public game.connection.packets.messages.ClientMessage.InputM getInput() {
    return input_ == null ? game.connection.packets.messages.ClientMessage.InputM.getDefaultInstance() : input_;
  }
  /**
   * <code>.connection.ClientMessage.InputM input = 2;</code>
   */
  @java.lang.Override
  public game.connection.packets.messages.ClientMessage.InputMOrBuilder getInputOrBuilder() {
    return input_ == null ? game.connection.packets.messages.ClientMessage.InputM.getDefaultInstance() : input_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getInput());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getInput());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof game.connection.packets.messages.ClientMessage)) {
      return super.equals(obj);
    }
    game.connection.packets.messages.ClientMessage other = (game.connection.packets.messages.ClientMessage) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (hasInput() != other.hasInput()) return false;
    if (hasInput()) {
      if (!getInput()
          .equals(other.getInput())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (hasInput()) {
      hash = (37 * hash) + INPUT_FIELD_NUMBER;
      hash = (53 * hash) + getInput().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static game.connection.packets.messages.ClientMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static game.connection.packets.messages.ClientMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static game.connection.packets.messages.ClientMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static game.connection.packets.messages.ClientMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static game.connection.packets.messages.ClientMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static game.connection.packets.messages.ClientMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static game.connection.packets.messages.ClientMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static game.connection.packets.messages.ClientMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static game.connection.packets.messages.ClientMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static game.connection.packets.messages.ClientMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static game.connection.packets.messages.ClientMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static game.connection.packets.messages.ClientMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(game.connection.packets.messages.ClientMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code connection.ClientMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:connection.ClientMessage)
      game.connection.packets.messages.ClientMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.connection.packets.messages.PacketMessages.internal_static_connection_ClientMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.connection.packets.messages.PacketMessages.internal_static_connection_ClientMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.connection.packets.messages.ClientMessage.class, game.connection.packets.messages.ClientMessage.Builder.class);
    }

    // Construct using game.connection.packets.messages.ClientMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getInputFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      input_ = null;
      if (inputBuilder_ != null) {
        inputBuilder_.dispose();
        inputBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return game.connection.packets.messages.PacketMessages.internal_static_connection_ClientMessage_descriptor;
    }

    @java.lang.Override
    public game.connection.packets.messages.ClientMessage getDefaultInstanceForType() {
      return game.connection.packets.messages.ClientMessage.getDefaultInstance();
    }

    @java.lang.Override
    public game.connection.packets.messages.ClientMessage build() {
      game.connection.packets.messages.ClientMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public game.connection.packets.messages.ClientMessage buildPartial() {
      game.connection.packets.messages.ClientMessage result = new game.connection.packets.messages.ClientMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(game.connection.packets.messages.ClientMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.input_ = inputBuilder_ == null
            ? input_
            : inputBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof game.connection.packets.messages.ClientMessage) {
        return mergeFrom((game.connection.packets.messages.ClientMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(game.connection.packets.messages.ClientMessage other) {
      if (other == game.connection.packets.messages.ClientMessage.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasInput()) {
        mergeInput(other.getInput());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getInputFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private game.connection.packets.messages.ClientMessage.InputM input_;
    private com.google.protobuf.SingleFieldBuilderV3<
        game.connection.packets.messages.ClientMessage.InputM, game.connection.packets.messages.ClientMessage.InputM.Builder, game.connection.packets.messages.ClientMessage.InputMOrBuilder> inputBuilder_;
    /**
     * <code>.connection.ClientMessage.InputM input = 2;</code>
     * @return Whether the input field is set.
     */
    public boolean hasInput() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.connection.ClientMessage.InputM input = 2;</code>
     * @return The input.
     */
    public game.connection.packets.messages.ClientMessage.InputM getInput() {
      if (inputBuilder_ == null) {
        return input_ == null ? game.connection.packets.messages.ClientMessage.InputM.getDefaultInstance() : input_;
      } else {
        return inputBuilder_.getMessage();
      }
    }
    /**
     * <code>.connection.ClientMessage.InputM input = 2;</code>
     */
    public Builder setInput(game.connection.packets.messages.ClientMessage.InputM value) {
      if (inputBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        input_ = value;
      } else {
        inputBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.connection.ClientMessage.InputM input = 2;</code>
     */
    public Builder setInput(
        game.connection.packets.messages.ClientMessage.InputM.Builder builderForValue) {
      if (inputBuilder_ == null) {
        input_ = builderForValue.build();
      } else {
        inputBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.connection.ClientMessage.InputM input = 2;</code>
     */
    public Builder mergeInput(game.connection.packets.messages.ClientMessage.InputM value) {
      if (inputBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          input_ != null &&
          input_ != game.connection.packets.messages.ClientMessage.InputM.getDefaultInstance()) {
          getInputBuilder().mergeFrom(value);
        } else {
          input_ = value;
        }
      } else {
        inputBuilder_.mergeFrom(value);
      }
      if (input_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.connection.ClientMessage.InputM input = 2;</code>
     */
    public Builder clearInput() {
      bitField0_ = (bitField0_ & ~0x00000002);
      input_ = null;
      if (inputBuilder_ != null) {
        inputBuilder_.dispose();
        inputBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.connection.ClientMessage.InputM input = 2;</code>
     */
    public game.connection.packets.messages.ClientMessage.InputM.Builder getInputBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getInputFieldBuilder().getBuilder();
    }
    /**
     * <code>.connection.ClientMessage.InputM input = 2;</code>
     */
    public game.connection.packets.messages.ClientMessage.InputMOrBuilder getInputOrBuilder() {
      if (inputBuilder_ != null) {
        return inputBuilder_.getMessageOrBuilder();
      } else {
        return input_ == null ?
            game.connection.packets.messages.ClientMessage.InputM.getDefaultInstance() : input_;
      }
    }
    /**
     * <code>.connection.ClientMessage.InputM input = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        game.connection.packets.messages.ClientMessage.InputM, game.connection.packets.messages.ClientMessage.InputM.Builder, game.connection.packets.messages.ClientMessage.InputMOrBuilder> 
        getInputFieldBuilder() {
      if (inputBuilder_ == null) {
        inputBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            game.connection.packets.messages.ClientMessage.InputM, game.connection.packets.messages.ClientMessage.InputM.Builder, game.connection.packets.messages.ClientMessage.InputMOrBuilder>(
                getInput(),
                getParentForChildren(),
                isClean());
        input_ = null;
      }
      return inputBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:connection.ClientMessage)
  }

  // @@protoc_insertion_point(class_scope:connection.ClientMessage)
  private static final game.connection.packets.messages.ClientMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new game.connection.packets.messages.ClientMessage();
  }

  public static game.connection.packets.messages.ClientMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientMessage>
      PARSER = new com.google.protobuf.AbstractParser<ClientMessage>() {
    @java.lang.Override
    public ClientMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ClientMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public game.connection.packets.messages.ClientMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

