// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

// Protobuf Java Version: 3.25.3
package game.connection.packets.messages;

public interface EdgeMOrBuilder extends
    // @@protoc_insertion_point(interface_extends:connection.EdgeM)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.connection.EdgeM.BodyEdgeM bep = 1;</code>
   * @return Whether the bep field is set.
   */
  boolean hasBep();
  /**
   * <code>.connection.EdgeM.BodyEdgeM bep = 1;</code>
   * @return The bep.
   */
  game.connection.packets.messages.EdgeM.BodyEdgeM getBep();
  /**
   * <code>.connection.EdgeM.BodyEdgeM bep = 1;</code>
   */
  game.connection.packets.messages.EdgeM.BodyEdgeMOrBuilder getBepOrBuilder();

  /**
   * <code>.connection.EdgeM.ControlEdgeM cep = 2;</code>
   * @return Whether the cep field is set.
   */
  boolean hasCep();
  /**
   * <code>.connection.EdgeM.ControlEdgeM cep = 2;</code>
   * @return The cep.
   */
  game.connection.packets.messages.EdgeM.ControlEdgeM getCep();
  /**
   * <code>.connection.EdgeM.ControlEdgeM cep = 2;</code>
   */
  game.connection.packets.messages.EdgeM.ControlEdgeMOrBuilder getCepOrBuilder();

  /**
   * <code>.connection.EdgeM.FixedEdgeM fep = 3;</code>
   * @return Whether the fep field is set.
   */
  boolean hasFep();
  /**
   * <code>.connection.EdgeM.FixedEdgeM fep = 3;</code>
   * @return The fep.
   */
  game.connection.packets.messages.EdgeM.FixedEdgeM getFep();
  /**
   * <code>.connection.EdgeM.FixedEdgeM fep = 3;</code>
   */
  game.connection.packets.messages.EdgeM.FixedEdgeMOrBuilder getFepOrBuilder();

  /**
   * <code>.connection.EdgeM.WorldEdgeM wei = 4;</code>
   * @return Whether the wei field is set.
   */
  boolean hasWei();
  /**
   * <code>.connection.EdgeM.WorldEdgeM wei = 4;</code>
   * @return The wei.
   */
  game.connection.packets.messages.EdgeM.WorldEdgeM getWei();
  /**
   * <code>.connection.EdgeM.WorldEdgeM wei = 4;</code>
   */
  game.connection.packets.messages.EdgeM.WorldEdgeMOrBuilder getWeiOrBuilder();

  game.connection.packets.messages.EdgeM.EdgeCase getEdgeCase();
}
