// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

// Protobuf Java Version: 3.25.3
package game.connection.packets.messages;

public final class PacketMessages {
  private PacketMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_VectorM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_VectorM_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_EdgeM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_EdgeM_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_EdgeM_BodyEdgeM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_EdgeM_BodyEdgeM_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_EdgeM_ControlEdgeM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_EdgeM_ControlEdgeM_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_EdgeM_FixedEdgeM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_EdgeM_FixedEdgeM_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_EdgeM_WorldEdgeM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_EdgeM_WorldEdgeM_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_ClientMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_ClientMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_ClientMessage_InputM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_ClientMessage_InputM_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_ServerMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_ServerMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_ServerMessage_WorldM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_ServerMessage_WorldM_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_ServerMessage_WorldM_BodyM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_ServerMessage_WorldM_BodyM_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_ServerMessage_WorldM_BodyM_PointM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_ServerMessage_WorldM_BodyM_PointM_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_ServerMessage_WorldM_BodyM_ShellM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_ServerMessage_WorldM_BodyM_ShellM_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_ServerMessage_WorldM_BodyM_TurtleM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_ServerMessage_WorldM_BodyM_TurtleM_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_ServerMessage_WorldM_BodyM_TurtleM_SpinneretsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_ServerMessage_WorldM_BodyM_TurtleM_SpinneretsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_ServerMessage_WorldM_BodyM_WebM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_ServerMessage_WorldM_BodyM_WebM_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_ServerMessage_LobbyM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_ServerMessage_LobbyM_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_ServerMessage_AnimationM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_ServerMessage_AnimationM_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_ServerMessage_AnimationM_CollisionBurstM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_ServerMessage_AnimationM_CollisionBurstM_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_ServerMessage_AnimationM_CollisionBurstM_Color_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_ServerMessage_AnimationM_CollisionBurstM_Color_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_ServerMessage_AnimationM_ScreenShakeM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_ServerMessage_AnimationM_ScreenShakeM_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_ServerMessage_AnimationM_ShellSnapFlashM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_ServerMessage_AnimationM_ShellSnapFlashM_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\022\nconnection\"\035\n\007VectorM\022" +
      "\022\n\ncoordinate\030\001 \003(\021\"\231\003\n\005EdgeM\022*\n\003bep\030\001 \001" +
      "(\0132\033.connection.EdgeM.BodyEdgeMH\000\022-\n\003cep" +
      "\030\002 \001(\0132\036.connection.EdgeM.ControlEdgeMH\000" +
      "\022+\n\003fep\030\003 \001(\0132\034.connection.EdgeM.FixedEd" +
      "geMH\000\022+\n\003wei\030\004 \001(\0132\034.connection.EdgeM.Wo" +
      "rldEdgeMH\000\032/\n\tBodyEdgeM\022\n\n\002bi\030\001 \001(\005\022\n\n\002i" +
      "1\030\002 \001(\005\022\n\n\002i2\030\003 \001(\005\032&\n\014ControlEdgeM\022\n\n\002i" +
      "1\030\001 \001(\005\022\n\n\002i2\030\002 \001(\005\032/\n\nFixedEdgeM\022\n\n\002i1\030" +
      "\001 \001(\005\022\n\n\002i2\030\002 \001(\005\022\t\n\001d\030\003 \001(\021\032I\n\nWorldEdg" +
      "eM\022\n\n\002i1\030\001 \001(\005\022\n\n\002i2\030\002 \001(\005\022\013\n\003bi1\030\003 \001(\005\022" +
      "\013\n\003bi2\030\004 \001(\005\022\t\n\001d\030\005 \001(\021B\006\n\004edge\"\306\001\n\rClie" +
      "ntMessage\022\014\n\004name\030\001 \001(\t\022/\n\005input\030\002 \001(\0132 " +
      ".connection.ClientMessage.InputM\032v\n\006Inpu" +
      "tM\022%\n\010mousepos\030\001 \001(\0132\023.connection.Vector" +
      "M\022\020\n\010teleport\030\002 \001(\010\022\016\n\006create\030\003 \001(\010\022\020\n\010w" +
      "ebFling\030\004 \001(\010\022\021\n\tdetachWeb\030\005 \001(\010\"\344\016\n\rSer" +
      "verMessage\022\017\n\007playing\030\001 \001(\010\022/\n\005world\030\002 \001" +
      "(\0132 .connection.ServerMessage.WorldM\022/\n\005" +
      "lobby\030\003 \001(\0132 .connection.ServerMessage.L" +
      "obbyM\0227\n\tanimation\030\004 \003(\0132$.connection.Se" +
      "rverMessage.AnimationM\022.\n\005sound\030\005 \003(\0162\037." +
      "connection.ServerMessage.Sound\032\217\010\n\006World" +
      "M\0224\n\004body\030\001 \003(\0132&.connection.ServerMessa" +
      "ge.WorldM.BodyM\032\316\007\n\005BodyM\022\037\n\004edge\030\001 \003(\0132" +
      "\021.connection.EdgeM\022<\n\005point\030\002 \003(\0132-.conn" +
      "ection.ServerMessage.WorldM.BodyM.PointM" +
      "\022\r\n\005bound\030\003 \003(\005\022>\n\005shell\030\004 \001(\0132-.connect" +
      "ion.ServerMessage.WorldM.BodyM.ShellMH\000\022" +
      "@\n\006turtle\030\005 \001(\0132..connection.ServerMessa" +
      "ge.WorldM.BodyM.TurtleMH\000\022:\n\003web\030\006 \001(\0132+" +
      ".connection.ServerMessage.WorldM.BodyM.W" +
      "ebMH\000\0328\n\006PointM\022 \n\003pos\030\001 \001(\0132\023.connectio" +
      "n.VectorM\022\014\n\004mass\030\002 \001(\005\032_\n\006ShellM\022\016\n\006par" +
      "ent\030\001 \001(\005\022\027\n\017leaveParentFlag\030\002 \001(\010\022,\n\006st" +
      "raps\030\003 \003(\0132\034.connection.EdgeM.WorldEdgeM" +
      "\032\256\001\n\007TurtleM\022R\n\nspinnerets\030\001 \003(\0132>.conne" +
      "ction.ServerMessage.WorldM.BodyM.TurtleM" +
      ".SpinneretsEntry\022\r\n\005shell\030\002 \001(\005\022\r\n\005owner" +
      "\030\003 \001(\005\0321\n\017SpinneretsEntry\022\013\n\003key\030\001 \001(\005\022\r" +
      "\n\005value\030\002 \001(\005:\0028\001\032\275\002\n\004WebM\0220\n\006target\030\001 \001" +
      "(\0132\033.connection.EdgeM.BodyEdgeMH\000\210\001\001\022\017\n\007" +
      "control\030\002 \001(\005\0225\n\nsourceEdge\030\003 \001(\0132\034.conn" +
      "ection.EdgeM.WorldEdgeMH\001\210\001\001\0226\n\013targetEd" +
      "ge1\030\004 \001(\0132\034.connection.EdgeM.WorldEdgeMH" +
      "\002\210\001\001\0226\n\013targetEdge2\030\005 \001(\0132\034.connection.E" +
      "dgeM.WorldEdgeMH\003\210\001\001\022\021\n\tisGrowing\030\006 \001(\010B" +
      "\t\n\007_targetB\r\n\013_sourceEdgeB\016\n\014_targetEdge" +
      "1B\016\n\014_targetEdge2B\r\n\013subtypeData\032+\n\006Lobb" +
      "yM\022\022\n\nplayerName\030\001 \003(\t\022\r\n\005score\030\002 \003(\005\032\372\003" +
      "\n\nAnimationM\022O\n\017collisionBurstM\030\001 \001(\01324." +
      "connection.ServerMessage.AnimationM.Coll" +
      "isionBurstMH\000\022I\n\014screenShakeM\030\002 \001(\01321.co" +
      "nnection.ServerMessage.AnimationM.Screen" +
      "ShakeMH\000\022O\n\017shellSnapFlashM\030\003 \001(\01324.conn" +
      "ection.ServerMessage.AnimationM.ShellSna" +
      "pFlashMH\000\032\273\001\n\017CollisionBurstM\022 \n\003pos\030\001 \001" +
      "(\0132\023.connection.VectorM\022\021\n\tintensity\030\002 \001" +
      "(\005\022I\n\005color\030\003 \001(\0132:.connection.ServerMes" +
      "sage.AnimationM.CollisionBurstM.Color\032(\n" +
      "\005Color\022\t\n\001R\030\001 \001(\005\022\t\n\001G\030\002 \001(\005\022\t\n\001B\030\003 \001(\005\032" +
      "!\n\014ScreenShakeM\022\021\n\tintensity\030\001 \001(\005\032\021\n\017Sh" +
      "ellSnapFlashMB\013\n\tanimation\";\n\005Sound\022\t\n\005d" +
      "eath\020\000\022\n\n\006button\020\001\022\014\n\010webThrow\020\002\022\r\n\tcoll" +
      "ision\020\003B4\n game.connection.packets.messa" +
      "gesB\016PacketMessagesP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_connection_VectorM_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_connection_VectorM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_VectorM_descriptor,
        new java.lang.String[] { "Coordinate", });
    internal_static_connection_EdgeM_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_connection_EdgeM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_EdgeM_descriptor,
        new java.lang.String[] { "Bep", "Cep", "Fep", "Wei", "Edge", });
    internal_static_connection_EdgeM_BodyEdgeM_descriptor =
      internal_static_connection_EdgeM_descriptor.getNestedTypes().get(0);
    internal_static_connection_EdgeM_BodyEdgeM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_EdgeM_BodyEdgeM_descriptor,
        new java.lang.String[] { "Bi", "I1", "I2", });
    internal_static_connection_EdgeM_ControlEdgeM_descriptor =
      internal_static_connection_EdgeM_descriptor.getNestedTypes().get(1);
    internal_static_connection_EdgeM_ControlEdgeM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_EdgeM_ControlEdgeM_descriptor,
        new java.lang.String[] { "I1", "I2", });
    internal_static_connection_EdgeM_FixedEdgeM_descriptor =
      internal_static_connection_EdgeM_descriptor.getNestedTypes().get(2);
    internal_static_connection_EdgeM_FixedEdgeM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_EdgeM_FixedEdgeM_descriptor,
        new java.lang.String[] { "I1", "I2", "D", });
    internal_static_connection_EdgeM_WorldEdgeM_descriptor =
      internal_static_connection_EdgeM_descriptor.getNestedTypes().get(3);
    internal_static_connection_EdgeM_WorldEdgeM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_EdgeM_WorldEdgeM_descriptor,
        new java.lang.String[] { "I1", "I2", "Bi1", "Bi2", "D", });
    internal_static_connection_ClientMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_connection_ClientMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_ClientMessage_descriptor,
        new java.lang.String[] { "Name", "Input", });
    internal_static_connection_ClientMessage_InputM_descriptor =
      internal_static_connection_ClientMessage_descriptor.getNestedTypes().get(0);
    internal_static_connection_ClientMessage_InputM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_ClientMessage_InputM_descriptor,
        new java.lang.String[] { "Mousepos", "Teleport", "Create", "WebFling", "DetachWeb", });
    internal_static_connection_ServerMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_connection_ServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_ServerMessage_descriptor,
        new java.lang.String[] { "Playing", "World", "Lobby", "Animation", "Sound", });
    internal_static_connection_ServerMessage_WorldM_descriptor =
      internal_static_connection_ServerMessage_descriptor.getNestedTypes().get(0);
    internal_static_connection_ServerMessage_WorldM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_ServerMessage_WorldM_descriptor,
        new java.lang.String[] { "Body", });
    internal_static_connection_ServerMessage_WorldM_BodyM_descriptor =
      internal_static_connection_ServerMessage_WorldM_descriptor.getNestedTypes().get(0);
    internal_static_connection_ServerMessage_WorldM_BodyM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_ServerMessage_WorldM_BodyM_descriptor,
        new java.lang.String[] { "Edge", "Point", "Bound", "Shell", "Turtle", "Web", "SubtypeData", });
    internal_static_connection_ServerMessage_WorldM_BodyM_PointM_descriptor =
      internal_static_connection_ServerMessage_WorldM_BodyM_descriptor.getNestedTypes().get(0);
    internal_static_connection_ServerMessage_WorldM_BodyM_PointM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_ServerMessage_WorldM_BodyM_PointM_descriptor,
        new java.lang.String[] { "Pos", "Mass", });
    internal_static_connection_ServerMessage_WorldM_BodyM_ShellM_descriptor =
      internal_static_connection_ServerMessage_WorldM_BodyM_descriptor.getNestedTypes().get(1);
    internal_static_connection_ServerMessage_WorldM_BodyM_ShellM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_ServerMessage_WorldM_BodyM_ShellM_descriptor,
        new java.lang.String[] { "Parent", "LeaveParentFlag", "Straps", });
    internal_static_connection_ServerMessage_WorldM_BodyM_TurtleM_descriptor =
      internal_static_connection_ServerMessage_WorldM_BodyM_descriptor.getNestedTypes().get(2);
    internal_static_connection_ServerMessage_WorldM_BodyM_TurtleM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_ServerMessage_WorldM_BodyM_TurtleM_descriptor,
        new java.lang.String[] { "Spinnerets", "Shell", "Owner", });
    internal_static_connection_ServerMessage_WorldM_BodyM_TurtleM_SpinneretsEntry_descriptor =
      internal_static_connection_ServerMessage_WorldM_BodyM_TurtleM_descriptor.getNestedTypes().get(0);
    internal_static_connection_ServerMessage_WorldM_BodyM_TurtleM_SpinneretsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_ServerMessage_WorldM_BodyM_TurtleM_SpinneretsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_connection_ServerMessage_WorldM_BodyM_WebM_descriptor =
      internal_static_connection_ServerMessage_WorldM_BodyM_descriptor.getNestedTypes().get(3);
    internal_static_connection_ServerMessage_WorldM_BodyM_WebM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_ServerMessage_WorldM_BodyM_WebM_descriptor,
        new java.lang.String[] { "Target", "Control", "SourceEdge", "TargetEdge1", "TargetEdge2", "IsGrowing", });
    internal_static_connection_ServerMessage_LobbyM_descriptor =
      internal_static_connection_ServerMessage_descriptor.getNestedTypes().get(1);
    internal_static_connection_ServerMessage_LobbyM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_ServerMessage_LobbyM_descriptor,
        new java.lang.String[] { "PlayerName", "Score", });
    internal_static_connection_ServerMessage_AnimationM_descriptor =
      internal_static_connection_ServerMessage_descriptor.getNestedTypes().get(2);
    internal_static_connection_ServerMessage_AnimationM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_ServerMessage_AnimationM_descriptor,
        new java.lang.String[] { "CollisionBurstM", "ScreenShakeM", "ShellSnapFlashM", "Animation", });
    internal_static_connection_ServerMessage_AnimationM_CollisionBurstM_descriptor =
      internal_static_connection_ServerMessage_AnimationM_descriptor.getNestedTypes().get(0);
    internal_static_connection_ServerMessage_AnimationM_CollisionBurstM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_ServerMessage_AnimationM_CollisionBurstM_descriptor,
        new java.lang.String[] { "Pos", "Intensity", "Color", });
    internal_static_connection_ServerMessage_AnimationM_CollisionBurstM_Color_descriptor =
      internal_static_connection_ServerMessage_AnimationM_CollisionBurstM_descriptor.getNestedTypes().get(0);
    internal_static_connection_ServerMessage_AnimationM_CollisionBurstM_Color_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_ServerMessage_AnimationM_CollisionBurstM_Color_descriptor,
        new java.lang.String[] { "R", "G", "B", });
    internal_static_connection_ServerMessage_AnimationM_ScreenShakeM_descriptor =
      internal_static_connection_ServerMessage_AnimationM_descriptor.getNestedTypes().get(1);
    internal_static_connection_ServerMessage_AnimationM_ScreenShakeM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_ServerMessage_AnimationM_ScreenShakeM_descriptor,
        new java.lang.String[] { "Intensity", });
    internal_static_connection_ServerMessage_AnimationM_ShellSnapFlashM_descriptor =
      internal_static_connection_ServerMessage_AnimationM_descriptor.getNestedTypes().get(2);
    internal_static_connection_ServerMessage_AnimationM_ShellSnapFlashM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_ServerMessage_AnimationM_ShellSnapFlashM_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
