// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

// Protobuf Java Version: 3.25.3
package game.connection.packets.messages;

public interface ServerMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:connection.ServerMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool playing = 1;</code>
   * @return The playing.
   */
  boolean getPlaying();

  /**
   * <code>.connection.ServerMessage.WorldM world = 2;</code>
   * @return Whether the world field is set.
   */
  boolean hasWorld();
  /**
   * <code>.connection.ServerMessage.WorldM world = 2;</code>
   * @return The world.
   */
  game.connection.packets.messages.ServerMessage.WorldM getWorld();
  /**
   * <code>.connection.ServerMessage.WorldM world = 2;</code>
   */
  game.connection.packets.messages.ServerMessage.WorldMOrBuilder getWorldOrBuilder();

  /**
   * <code>.connection.ServerMessage.LobbyM lobby = 3;</code>
   * @return Whether the lobby field is set.
   */
  boolean hasLobby();
  /**
   * <code>.connection.ServerMessage.LobbyM lobby = 3;</code>
   * @return The lobby.
   */
  game.connection.packets.messages.ServerMessage.LobbyM getLobby();
  /**
   * <code>.connection.ServerMessage.LobbyM lobby = 3;</code>
   */
  game.connection.packets.messages.ServerMessage.LobbyMOrBuilder getLobbyOrBuilder();

  /**
   * <code>repeated .connection.ServerMessage.AnimationM animation = 4;</code>
   */
  java.util.List<game.connection.packets.messages.ServerMessage.AnimationM> 
      getAnimationList();
  /**
   * <code>repeated .connection.ServerMessage.AnimationM animation = 4;</code>
   */
  game.connection.packets.messages.ServerMessage.AnimationM getAnimation(int index);
  /**
   * <code>repeated .connection.ServerMessage.AnimationM animation = 4;</code>
   */
  int getAnimationCount();
  /**
   * <code>repeated .connection.ServerMessage.AnimationM animation = 4;</code>
   */
  java.util.List<? extends game.connection.packets.messages.ServerMessage.AnimationMOrBuilder> 
      getAnimationOrBuilderList();
  /**
   * <code>repeated .connection.ServerMessage.AnimationM animation = 4;</code>
   */
  game.connection.packets.messages.ServerMessage.AnimationMOrBuilder getAnimationOrBuilder(
      int index);

  /**
   * <code>repeated .connection.ServerMessage.Sound sound = 5;</code>
   * @return A list containing the sound.
   */
  java.util.List<game.connection.packets.messages.ServerMessage.Sound> getSoundList();
  /**
   * <code>repeated .connection.ServerMessage.Sound sound = 5;</code>
   * @return The count of sound.
   */
  int getSoundCount();
  /**
   * <code>repeated .connection.ServerMessage.Sound sound = 5;</code>
   * @param index The index of the element to return.
   * @return The sound at the given index.
   */
  game.connection.packets.messages.ServerMessage.Sound getSound(int index);
  /**
   * <code>repeated .connection.ServerMessage.Sound sound = 5;</code>
   * @return A list containing the enum numeric values on the wire for sound.
   */
  java.util.List<java.lang.Integer>
  getSoundValueList();
  /**
   * <code>repeated .connection.ServerMessage.Sound sound = 5;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of sound at the given index.
   */
  int getSoundValue(int index);
}
