// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

// Protobuf Java Version: 3.25.3
package game.connection.packets.messages;

/**
 * Protobuf type {@code connection.VectorM}
 */
public final class VectorM extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:connection.VectorM)
    VectorMOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VectorM.newBuilder() to construct.
  private VectorM(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VectorM() {
    coordinate_ = emptyIntList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new VectorM();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return game.connection.packets.messages.PacketMessages.internal_static_connection_VectorM_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return game.connection.packets.messages.PacketMessages.internal_static_connection_VectorM_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            game.connection.packets.messages.VectorM.class, game.connection.packets.messages.VectorM.Builder.class);
  }

  public static final int COORDINATE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.IntList coordinate_ =
      emptyIntList();
  /**
   * <code>repeated sint32 coordinate = 1;</code>
   * @return A list containing the coordinate.
   */
  @java.lang.Override
  public java.util.List<java.lang.Integer>
      getCoordinateList() {
    return coordinate_;
  }
  /**
   * <code>repeated sint32 coordinate = 1;</code>
   * @return The count of coordinate.
   */
  public int getCoordinateCount() {
    return coordinate_.size();
  }
  /**
   * <code>repeated sint32 coordinate = 1;</code>
   * @param index The index of the element to return.
   * @return The coordinate at the given index.
   */
  public int getCoordinate(int index) {
    return coordinate_.getInt(index);
  }
  private int coordinateMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (getCoordinateList().size() > 0) {
      output.writeUInt32NoTag(10);
      output.writeUInt32NoTag(coordinateMemoizedSerializedSize);
    }
    for (int i = 0; i < coordinate_.size(); i++) {
      output.writeSInt32NoTag(coordinate_.getInt(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < coordinate_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeSInt32SizeNoTag(coordinate_.getInt(i));
      }
      size += dataSize;
      if (!getCoordinateList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      coordinateMemoizedSerializedSize = dataSize;
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof game.connection.packets.messages.VectorM)) {
      return super.equals(obj);
    }
    game.connection.packets.messages.VectorM other = (game.connection.packets.messages.VectorM) obj;

    if (!getCoordinateList()
        .equals(other.getCoordinateList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCoordinateCount() > 0) {
      hash = (37 * hash) + COORDINATE_FIELD_NUMBER;
      hash = (53 * hash) + getCoordinateList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static game.connection.packets.messages.VectorM parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static game.connection.packets.messages.VectorM parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static game.connection.packets.messages.VectorM parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static game.connection.packets.messages.VectorM parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static game.connection.packets.messages.VectorM parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static game.connection.packets.messages.VectorM parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static game.connection.packets.messages.VectorM parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static game.connection.packets.messages.VectorM parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static game.connection.packets.messages.VectorM parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static game.connection.packets.messages.VectorM parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static game.connection.packets.messages.VectorM parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static game.connection.packets.messages.VectorM parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(game.connection.packets.messages.VectorM prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code connection.VectorM}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:connection.VectorM)
      game.connection.packets.messages.VectorMOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return game.connection.packets.messages.PacketMessages.internal_static_connection_VectorM_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return game.connection.packets.messages.PacketMessages.internal_static_connection_VectorM_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              game.connection.packets.messages.VectorM.class, game.connection.packets.messages.VectorM.Builder.class);
    }

    // Construct using game.connection.packets.messages.VectorM.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      coordinate_ = emptyIntList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return game.connection.packets.messages.PacketMessages.internal_static_connection_VectorM_descriptor;
    }

    @java.lang.Override
    public game.connection.packets.messages.VectorM getDefaultInstanceForType() {
      return game.connection.packets.messages.VectorM.getDefaultInstance();
    }

    @java.lang.Override
    public game.connection.packets.messages.VectorM build() {
      game.connection.packets.messages.VectorM result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public game.connection.packets.messages.VectorM buildPartial() {
      game.connection.packets.messages.VectorM result = new game.connection.packets.messages.VectorM(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(game.connection.packets.messages.VectorM result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        coordinate_.makeImmutable();
        result.coordinate_ = coordinate_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof game.connection.packets.messages.VectorM) {
        return mergeFrom((game.connection.packets.messages.VectorM)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(game.connection.packets.messages.VectorM other) {
      if (other == game.connection.packets.messages.VectorM.getDefaultInstance()) return this;
      if (!other.coordinate_.isEmpty()) {
        if (coordinate_.isEmpty()) {
          coordinate_ = other.coordinate_;
          coordinate_.makeImmutable();
          bitField0_ |= 0x00000001;
        } else {
          ensureCoordinateIsMutable();
          coordinate_.addAll(other.coordinate_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int v = input.readSInt32();
              ensureCoordinateIsMutable();
              coordinate_.addInt(v);
              break;
            } // case 8
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              ensureCoordinateIsMutable();
              while (input.getBytesUntilLimit() > 0) {
                coordinate_.addInt(input.readSInt32());
              }
              input.popLimit(limit);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.IntList coordinate_ = emptyIntList();
    private void ensureCoordinateIsMutable() {
      if (!coordinate_.isModifiable()) {
        coordinate_ = makeMutableCopy(coordinate_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated sint32 coordinate = 1;</code>
     * @return A list containing the coordinate.
     */
    public java.util.List<java.lang.Integer>
        getCoordinateList() {
      coordinate_.makeImmutable();
      return coordinate_;
    }
    /**
     * <code>repeated sint32 coordinate = 1;</code>
     * @return The count of coordinate.
     */
    public int getCoordinateCount() {
      return coordinate_.size();
    }
    /**
     * <code>repeated sint32 coordinate = 1;</code>
     * @param index The index of the element to return.
     * @return The coordinate at the given index.
     */
    public int getCoordinate(int index) {
      return coordinate_.getInt(index);
    }
    /**
     * <code>repeated sint32 coordinate = 1;</code>
     * @param index The index to set the value at.
     * @param value The coordinate to set.
     * @return This builder for chaining.
     */
    public Builder setCoordinate(
        int index, int value) {

      ensureCoordinateIsMutable();
      coordinate_.setInt(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated sint32 coordinate = 1;</code>
     * @param value The coordinate to add.
     * @return This builder for chaining.
     */
    public Builder addCoordinate(int value) {

      ensureCoordinateIsMutable();
      coordinate_.addInt(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated sint32 coordinate = 1;</code>
     * @param values The coordinate to add.
     * @return This builder for chaining.
     */
    public Builder addAllCoordinate(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureCoordinateIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, coordinate_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated sint32 coordinate = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCoordinate() {
      coordinate_ = emptyIntList();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:connection.VectorM)
  }

  // @@protoc_insertion_point(class_scope:connection.VectorM)
  private static final game.connection.packets.messages.VectorM DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new game.connection.packets.messages.VectorM();
  }

  public static game.connection.packets.messages.VectorM getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VectorM>
      PARSER = new com.google.protobuf.AbstractParser<VectorM>() {
    @java.lang.Override
    public VectorM parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VectorM> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VectorM> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public game.connection.packets.messages.VectorM getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

