// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

// Protobuf Java Version: 3.25.3
package game.connection.packets.messages;

public interface VectorMOrBuilder extends
    // @@protoc_insertion_point(interface_extends:connection.VectorM)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated sint32 coordinate = 1;</code>
   * @return A list containing the coordinate.
   */
  java.util.List<java.lang.Integer> getCoordinateList();
  /**
   * <code>repeated sint32 coordinate = 1;</code>
   * @return The count of coordinate.
   */
  int getCoordinateCount();
  /**
   * <code>repeated sint32 coordinate = 1;</code>
   * @param index The index of the element to return.
   * @return The coordinate at the given index.
   */
  int getCoordinate(int index);
}
